spring:
  application:
    name: Application name

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: mysqlURL
    username: username
    password: password
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true